### ISSUE TITLE
How to do more custom this slider

### ISSUE THREAD

**Issue by ErAshu** [nickypatson/GradientSlider#1]
Hi Nicky,
Thanks for the providing Slider.
I am attaching the screenshot, how can i achieve this.
I have background image and head of slider. 
![screen shot 2018-01-04 at 11 47 56 am](https://user-images.githubusercontent.com/4178384/34552096-78f64684-f145-11e7-8794-9221085f4cc4.png)

**Comment by nickypatson** [comment]
Instead of using gardientlayer use uiview. And subview to main view

**Comment by nickypatson** [comment]
Hope this works . Iam closing the issue
