### ISSUE TITLE
Track color.

### ISSUE THREAD

**Issue by Rogho** [nickypatson/GradientSlider#2]
Hey Nicky awesome work you've done there.
I was wondering whether I can keep the track color white from thumb point to end point of track.
Any hint on that?

**Comment by nickypatson** [comment]
Just keep the colorarray as white .. let me know its works

**Comment by Rogho** [comment]
![2018-01-4](https://user-images.githubusercontent.com/26385059/34602694-cd8d1ace-f226-11e7-9134-0bdf53de0c66.png)
I meant more like this.

**Comment by nickypatson** [comment]
Keep the color array with red and orange . Make sure to keep the locations value as 

track.locations = [0.0,0.5,1.0]

**Comment by Rogho** [comment]
![slice 1](https://user-images.githubusercontent.com/26385059/34602879-8cd76cd6-f227-11e7-988c-d930e398497d.png)
I meant more like this.

**Comment by nickypatson** [comment]
Create another view and  use the existing gradient view color array with red and orange and make sure to update location as track.locations = [0.0,0.5,1.0] and frame of the gradient layer .
